package com.xcompwiz.mystcraft.grammar;

import java.util.List;

/** Generated from Mystcraft Legacy 0.13.7.06 GrammarRules + SymbolRules. */
final class BuiltinLegacyGrammar {
    private BuiltinLegacyGrammar() {}

    static void registerAll() {
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Age", List.of("mystcraft:TerrainGen", "mystcraft:BiomeController", "mystcraft:Weather", "mystcraft:Lighting", "mystcraft:Spawning0", "mystcraft:Suns0", "mystcraft:Moons0", "mystcraft:Starfields0", "mystcraft:Doodads0", "mystcraft:Visuals0", "mystcraft:FeatureSmalls0", "mystcraft:FeatureMediums0", "mystcraft:FeatureLarges0", "mystcraft:Effects0"), 0));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Spawning0", List.of(), 10));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Biomes", List.of("mystcraft:BiomesAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BiomesAdv", List.of("mystcraft:BiomesAdv", "mystcraft:Biome"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BiomesAdv", List.of("mystcraft:Biome"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Biomes", List.of("mystcraft:BiomesExt", "mystcraft:Biome"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BiomesExt", List.of("mystcraft:BiomesExt", "mystcraft:Biomes"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BiomesExt", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Suns0", List.of("mystcraft:SunsAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:SunsAdv", List.of("mystcraft:SunsAdv", "mystcraft:Sun"), 4));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:SunsAdv", List.of("mystcraft:Sun"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Suns0", List.of("mystcraft:SunsExt", "mystcraft:Sun"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:SunsExt", List.of("mystcraft:SunsExt", "mystcraft:Sun"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:SunsExt", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Moons0", List.of("mystcraft:MoonsAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:MoonsAdv", List.of("mystcraft:MoonsAdv", "mystcraft:Moon"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:MoonsAdv", List.of("mystcraft:Moon"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Moons0", List.of("mystcraft:MoonsExt", "mystcraft:Moon"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:MoonsExt", List.of("mystcraft:MoonsExt", "mystcraft:Moon"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:MoonsExt", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Starfields0", List.of("mystcraft:StarfieldsAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:StarfieldsAdv", List.of("mystcraft:StarfieldsAdv", "mystcraft:Starfield"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:StarfieldsAdv", List.of("mystcraft:Starfield"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Starfields0", List.of("mystcraft:StarfieldsExt", "mystcraft:Starfield"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:StarfieldsExt", List.of("mystcraft:StarfieldsExt", "mystcraft:Starfield"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:StarfieldsExt", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Starfield", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Doodads0", List.of("mystcraft:DoodadsAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:DoodadsAdv", List.of("mystcraft:DoodadsAdv", "mystcraft:Doodad"), 5));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:DoodadsAdv", List.of("mystcraft:Doodad"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Doodads0", List.of("mystcraft:DoodadsExt", "mystcraft:Doodad"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:DoodadsExt", List.of("mystcraft:DoodadsExt", "mystcraft:Doodad"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:DoodadsExt", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Doodad", List.of(), 0));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visuals0", List.of("mystcraft:VisualsAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:VisualsAdv", List.of("mystcraft:VisualsAdv", "mystcraft:Visual"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:VisualsAdv", List.of("mystcraft:Visual"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visuals0", List.of("mystcraft:VisualsExt", "mystcraft:Visual"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:VisualsExt", List.of("mystcraft:VisualsExt", "mystcraft:Visual"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:VisualsExt", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLarges0", List.of("mystcraft:FeatureLargeAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLargeAdv", List.of("mystcraft:FeatureLargeAdv", "mystcraft:FeatureLarge"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLargeAdv", List.of("mystcraft:FeatureLarge"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLarges0", List.of("mystcraft:FeatureLargeExt", "mystcraft:FeatureLarge"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLargeExt", List.of("mystcraft:FeatureLargeExt", "mystcraft:FeatureLarge"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLargeExt", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLarge", List.of(), 4));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMediums0", List.of("mystcraft:FeatureMediumAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMediumAdv", List.of("mystcraft:FeatureMediumAdv", "mystcraft:FeatureMedium"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMediumAdv", List.of("mystcraft:FeatureMedium"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMediums0", List.of("mystcraft:FeatureMediumExt", "mystcraft:FeatureMedium"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMediumExt", List.of("mystcraft:FeatureMediumExt", "mystcraft:FeatureMedium"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMediumExt", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMedium", List.of(), 4));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmalls0", List.of("mystcraft:FeatureSmallAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmallAdv", List.of("mystcraft:FeatureSmallAdv", "mystcraft:FeatureSmall"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmallAdv", List.of("mystcraft:FeatureSmall"), 4));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmalls0", List.of("mystcraft:FeatureSmallExt", "mystcraft:FeatureSmall"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmallExt", List.of("mystcraft:FeatureSmallExt", "mystcraft:FeatureSmall"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmallExt", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmall", List.of(), 4));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Effects0", List.of("mystcraft:EffectsAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:EffectsAdv", List.of("mystcraft:EffectsAdv", "mystcraft:Effect"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:EffectsAdv", List.of("mystcraft:Effect"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Effects0", List.of("mystcraft:EffectsExt", "mystcraft:Effect"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:EffectsExt", List.of("mystcraft:EffectsExt", "mystcraft:Effect"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:EffectsExt", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Effect", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:SunsetUncommon", List.of(), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:SunsetUncommon", List.of("mystcraft:Sunset"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Sunset", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Sunset_Ext", List.of("mystcraft:Sunset"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Sunset_Ext", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Angle", List.of("mystcraft:AngleAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:AngleAdv", List.of("mystcraft:AngleAdv", "mystcraft:AngleBasic"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:AngleAdv", List.of("mystcraft:AngleBasic"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Angle", List.of("mystcraft:Angle_Ext", "mystcraft:AngleBasic"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Angle_Ext", List.of("mystcraft:Angle"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Angle_Ext", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Period", List.of("mystcraft:PeriodAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:PeriodAdv", List.of("mystcraft:PeriodAdv", "mystcraft:PeriodBasic"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:PeriodAdv", List.of("mystcraft:PeriodBasic"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Period", List.of("mystcraft:Period_Ext", "mystcraft:PeriodBasic"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Period_Ext", List.of("mystcraft:Period"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Period_Ext", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Phase", List.of("mystcraft:PhaseAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:PhaseAdv", List.of("mystcraft:PhaseAdv", "mystcraft:PhaseBasic"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:PhaseAdv", List.of("mystcraft:PhaseBasic"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Phase", List.of("mystcraft:Phase_Ext", "mystcraft:PhaseBasic"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Phase_Ext", List.of("mystcraft:Phase"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Phase_Ext", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Color", List.of("mystcraft:ColorAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorAdv", List.of("mystcraft:ColorAdv", "mystcraft:ColorBasic"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorAdv", List.of("mystcraft:ColorBasic"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Color", List.of("mystcraft:Color_Ext", "mystcraft:ColorBasic"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Color_Ext", List.of("mystcraft:Color"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Color_Ext", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Gradient", List.of("mystcraft:GradientAdv"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:GradientAdv", List.of("mystcraft:GradientAdv", "mystcraft:GradientBasic"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:GradientAdv", List.of("mystcraft:GradientBasic"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Gradient", List.of("mystcraft:Gradient_Ext", "mystcraft:GradientBasic"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Gradient_Ext", List.of("mystcraft:Gradient"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Gradient_Ext", List.of(), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BlockTerrain", List.of(), 0));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BlockSolid", List.of(), 0));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BlockStructure", List.of(), 0));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BlockOrganic", List.of(), 0));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BlockCrystal", List.of(), 0));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BlockSea", List.of(), 0));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BlockFluid", List.of(), 0));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BlockGas", List.of(), 0));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BlockAny", List.of(), 0));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BLOCK_NONSOLID", List.of("mystcraft:BlockFluid"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BLOCK_NONSOLID", List.of("mystcraft:BlockGas"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:AngleBasic", List.of("mystcraft:ModNorth"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:AngleBasic", List.of("mystcraft:ModSouth"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:AngleBasic", List.of("mystcraft:ModEast"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:AngleBasic", List.of("mystcraft:ModWest"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:PhaseBasic", List.of("mystcraft:ModRising"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:PhaseBasic", List.of("mystcraft:ModNoon"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:PhaseBasic", List.of("mystcraft:ModSetting"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:PhaseBasic", List.of("mystcraft:ModEnd"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:PeriodBasic", List.of("mystcraft:ModZero"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:PeriodBasic", List.of("mystcraft:ModHalf"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:PeriodBasic", List.of("mystcraft:ModFull"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:PeriodBasic", List.of("mystcraft:ModDouble"), 1));

        // CP255: restore the dynamic SymbolColor grammar bindings from 0.13.7.06 SymbolColor#getGrammarRules().
        // Without these rules explicit ModColor* pages cannot satisfy ColorBasic; Grammar completion then
        // inserts the literal ColorBasic token and may build unrelated extra gradients/celestials around it.
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorMaroon"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorRed"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorOlive"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorYellow"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorDarkGreen"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorGreen"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorTeal"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorCyan"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorNavy"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorBlue"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorPurple"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorMagenta"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorBlack"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorGrey"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorSilver"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:ColorBasic", List.of("mystcraft:ModColorWhite"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:GradientBasic", List.of("mystcraft:Color", "mystcraft:Period", "mystcraft:ModGradient"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Sunset", List.of("mystcraft:Sunset_Ext", "mystcraft:Gradient", "mystcraft:ColorHorizon"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BlockSea", List.of("mystcraft:NoSea"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Weather", List.of("mystcraft:WeatherOff"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Weather", List.of("mystcraft:WeatherStorm"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Weather", List.of("mystcraft:WeatherSnow"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Weather", List.of("mystcraft:WeatherRain"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Weather", List.of("mystcraft:WeatherCloudy"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Weather", List.of("mystcraft:WeatherOn"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Weather", List.of("mystcraft:WeatherSlow"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Weather", List.of("mystcraft:WeatherNorm"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Weather", List.of("mystcraft:WeatherFast"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:TerrainGen", List.of("mystcraft:TerrainVoid"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:TerrainGen", List.of("mystcraft:BlockTerrain", "mystcraft:BlockSea", "mystcraft:TerrainNormal"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:TerrainGen", List.of("mystcraft:BlockTerrain", "mystcraft:BlockSea", "mystcraft:TerrainAmplified"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:TerrainGen", List.of("mystcraft:BlockTerrain", "mystcraft:BlockSea", "mystcraft:TerrainNether"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:TerrainGen", List.of("mystcraft:BlockTerrain", "mystcraft:BlockSea", "mystcraft:TerrainFlat"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:TerrainGen", List.of("mystcraft:BlockTerrain", "mystcraft:BlockSea", "mystcraft:TerrainEnd"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Lighting", List.of("mystcraft:LightingNormal"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Lighting", List.of("mystcraft:LightingDark"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Lighting", List.of("mystcraft:LightingBright"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:Gradient", "mystcraft:ColorFog"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:Gradient", "mystcraft:ColorSkyNight"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:Gradient", "mystcraft:ColorSky"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:Gradient", "mystcraft:ColorCloud"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:Color", "mystcraft:ColorGrass"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:Color", "mystcraft:ColorFoliage"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:Color", "mystcraft:ColorWater"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:ColorFogNat"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:ColorSkyNat"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:ColorCloudNat"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:ColorGrassNat"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:ColorFoliageNat"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:ColorWaterNat"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:NoHorizon"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Visual", List.of("mystcraft:Angle", "mystcraft:Rainbow"), 4));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Effect", List.of("mystcraft:EnvScorch"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Effect", List.of("mystcraft:EnvMeteor"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Effect", List.of("mystcraft:Gradient", "mystcraft:EnvLightning"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Effect", List.of("mystcraft:EnvExplosions"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Effect", List.of("mystcraft:EnvAccel"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Starfield", List.of("mystcraft:Gradient", "mystcraft:StarsEndSky"), 4));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Starfield", List.of("mystcraft:Gradient", "mystcraft:Period", "mystcraft:Angle", "mystcraft:StarsNormal"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Starfield", List.of("mystcraft:Gradient", "mystcraft:Period", "mystcraft:Angle", "mystcraft:StarsTwinkle"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Starfield", List.of("mystcraft:StarsDark"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Sun", List.of("mystcraft:Sunset", "mystcraft:Period", "mystcraft:Angle", "mystcraft:Phase", "mystcraft:SunNormal"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Sun", List.of("mystcraft:SunDark"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Moon", List.of("mystcraft:SunsetUncommon", "mystcraft:Period", "mystcraft:Angle", "mystcraft:Phase", "mystcraft:MoonNormal"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:Moon", List.of("mystcraft:MoonDark"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BiomeController", List.of("mystcraft:BioConNative"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BiomeController", List.of("mystcraft:Biome", "mystcraft:BioConSingle"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BiomeController", List.of("mystcraft:Biomes", "mystcraft:Biome", "mystcraft:BioConTiled"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BiomeController", List.of("mystcraft:Biomes", "mystcraft:Biome", "mystcraft:BioConGrid"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BiomeController", List.of("mystcraft:Biomes", "mystcraft:Biome", "mystcraft:Biome", "mystcraft:BioConTiny"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BiomeController", List.of("mystcraft:Biomes", "mystcraft:Biome", "mystcraft:Biome", "mystcraft:BioConSmall"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BiomeController", List.of("mystcraft:Biomes", "mystcraft:Biome", "mystcraft:Biome", "mystcraft:BioConMedium"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BiomeController", List.of("mystcraft:Biomes", "mystcraft:Biome", "mystcraft:Biome", "mystcraft:BioConLarge"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:BiomeController", List.of("mystcraft:Biomes", "mystcraft:Biome", "mystcraft:Biome", "mystcraft:BioConHuge"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLarge", List.of("mystcraft:Biome", "mystcraft:BlockStructure", "mystcraft:FloatIslands"), 4));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLarge", List.of("mystcraft:BlockStructure", "mystcraft:Tendrils"), 4));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLarge", List.of("mystcraft:Skylands"), 5));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLarge", List.of("mystcraft:Caves"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLarge", List.of("mystcraft:DenseOres"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLarge", List.of("mystcraft:HugeTrees"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMedium", List.of("mystcraft:NetherFort"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMedium", List.of("mystcraft:Villages"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMedium", List.of("mystcraft:Strongholds"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMedium", List.of("mystcraft:Mineshafts"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMedium", List.of("mystcraft:Ravines"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMedium", List.of("mystcraft:BlockStructure", "mystcraft:TerModSpheres"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMedium", List.of("mystcraft:Dungeons"), 2));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMedium", List.of("mystcraft:BlockStructure", "mystcraft:GenSpikes"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmall", List.of("mystcraft:StarFissure"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmall", List.of("mystcraft:BlockStructure", "mystcraft:Obelisks"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmall", List.of("mystcraft:BlockFluid", "mystcraft:LakesSurface"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmall", List.of("mystcraft:BLOCK_NONSOLID", "mystcraft:LakesDeep"), 1));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmall", List.of("mystcraft:BlockCrystal", "mystcraft:CryForm"), 3));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLarges0", List.of("mystcraft:FeatureLargeExt", "mystcraft:FeatureLargeDummy"), 5));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMediums0", List.of("mystcraft:FeatureMediumExt", "mystcraft:FeatureMediumDummy"), 5));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmalls0", List.of("mystcraft:FeatureSmallExt", "mystcraft:FeatureSmallDummy"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureLargeExt", List.of("mystcraft:FeatureLargeDummy"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureMediumExt", List.of("mystcraft:FeatureMediumDummy"), null));
        GrammarRuleRegistry.register(new GrammarRule("mystcraft:FeatureSmallExt", List.of("mystcraft:FeatureSmallDummy"), null));
    }
}
