package com.xcompwiz.mystcraft.world.dimension;

import com.xcompwiz.mystcraft.registry.MystBlocks;
import com.xcompwiz.mystcraft.world.agedata.AgeRecord;
import com.xcompwiz.mystcraft.world.worldgen.AgeLegacyPopulationSeedMath;
import com.xcompwiz.mystcraft.world.worldgen.AgeStarFissureLegacyPlan;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;

import java.util.Random;

/** One-shot server-thread application of the ordered Legacy Star Fissure population decision. */
public final class AgeStarFissureRuntime {
    private static final String SYMBOL = "mystcraft:StarFissure";

    public enum Outcome {
        NONE(false, false),
        GENERATED(true, true),
        SUPPRESSED(true, false);

        private final boolean processedNow;
        private final boolean generated;

        Outcome(boolean processedNow, boolean generated) {
            this.processedNow = processedNow;
            this.generated = generated;
        }

        public boolean processedNow() { return processedNow; }
        public boolean generated() { return generated; }
    }

    private AgeStarFissureRuntime() {}

    /**
     * Completes the Star Fissure one-shot after the persistent spawn has been selected.
     *
     * <p>For a fresh Age, forcing the spawn chunk to FULL runs the ordered Legacy population
     * batch. That batch either stages the Star Fissure plan at its authored Symbol position or
     * records suppression by an earlier successful Village. Existing pre-I66 chunks that were
     * already FULL cannot produce that transient plan; those use the old deterministic boundary-
     * seed fallback so upgraded development saves never permanently lose their fissure.</p>
     */
    public static Outcome ensureProcessed(ServerLevel level, AgeRecord age) {
        if (age.starFissureProcessed() || !age.symbols().contains(SYMBOL)) return Outcome.NONE;

        BlockPos spawn = level.getSharedSpawnPos();
        int spawnChunkX = Math.floorDiv(spawn.getX(), 16);
        int spawnChunkZ = Math.floorDiv(spawn.getZ(), 16);

        // Spawn is already durable and installed on ServerLevel before this call. Generating the
        // chunk now therefore lets SymbolStarFissure identify its Legacy spawn-chunk condition.
        level.getChunk(spawnChunkX, spawnChunkZ);

        AgeStarFissurePopulationBridge.Pending pending =
                AgeStarFissurePopulationBridge.take(level, spawnChunkX, spawnChunkZ);
        if (pending != null) {
            if (pending.kind() == AgeStarFissurePopulationBridge.Kind.SUPPRESSED) {
                return Outcome.SUPPRESSED;
            }
            apply(level, pending.plan());
            return Outcome.GENERATED;
        }

        // Compatibility fallback for a chunk that was already generated by an earlier checkpoint.
        // This preserves the real ChunkProviderMyst population boundary seed, but cannot recover
        // the unknown pre-Star-Fissure draws from the old already-finished population stream.
        long seed = AgeLegacyPopulationSeedMath.populationBoundarySeed(
                age.seed(), spawnChunkX, spawnChunkZ);
        Random random = new Random(seed);
        AgeStarFissureLegacyPlan.Plan fallback = AgeStarFissureLegacyPlan.create(
                spawnChunkX << 4, spawnChunkZ << 4, random::nextInt);
        apply(level, fallback);
        return Outcome.GENERATED;
    }

    static void apply(ServerLevel level, AgeStarFissureLegacyPlan.Plan plan) {
        BlockState fissure = MystBlocks.STAR_FISSURE.get().defaultBlockState();
        int[][] noise = plan.noise();
        for (int row = 0; row < noise.length; ++row) {
            for (int x = noise[row][0]; x <= noise[row][1]; ++x) {
                setColumn(level, fissure, new BlockPos(plan.originX() + x, level.getMinBuildHeight(), plan.originZ() + row * 2));
                setColumn(level, fissure, new BlockPos(plan.originX() + x, level.getMinBuildHeight(), plan.originZ() + row * 2 + 1));
            }
        }
    }

    private static void setColumn(ServerLevel level, BlockState fissure, BlockPos base) {
        level.setBlock(base, fissure, 2);
        int top = level.getMaxBuildHeight();
        for (int y = base.getY() + 1; y < top; ++y) {
            level.setBlock(new BlockPos(base.getX(), y, base.getZ()), Blocks.AIR.defaultBlockState(), 2);
        }
    }
}
