package com.xcompwiz.mystcraft.symbol;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.material.Fluid;
import net.minecraft.world.level.material.Fluids;
import net.neoforged.neoforge.fluids.FluidStack;
import net.neoforged.neoforge.fluids.FluidType;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.HashSet;
import java.util.Set;

/**
 * Built-in dynamic block/fluid modifier symbols from Mystcraft Legacy 0.13.7.06.
 *
 * <p>These were generated by ModSymbolsModifiers.initialize() rather than the fixed
 * ModSymbols.initialize() table, hence they live beside rather than inside the fixed
 * 110-symbol registry.</p>
 */
public final class LegacyMaterialSymbolRegistry {
    private static final Map<String, LegacyMaterialSymbolDefinition> BY_LEGACY_ID = new LinkedHashMap<>();
    private static final Set<String> RUNTIME_FLUID_IDS = new HashSet<>();
    private static final Set<ResourceLocation> FLUID_BLACKLIST = new HashSet<>();
    private static final Map<ResourceLocation, RuntimeFluidOptions> FLUID_OPTIONS = new LinkedHashMap<>();
    private static boolean bootstrapped;
    private static boolean runtimeFluidsDirty = true;

    private LegacyMaterialSymbolRegistry() {}

    public static synchronized void bootstrapDefaults() {
        if (bootstrapped) return;
        register(def("mystcraft:ModMat_dirt_0", "minecraft:dirt", 0, "minecraft:dirt", "Terrain", 2, List.of(bind("mystcraft:BlockTerrain", 4), bind("mystcraft:BlockStructure", 2), bind("mystcraft:BlockSolid", 1))));
        register(def("mystcraft:ModMat_stone_0", "minecraft:stone", 0, "minecraft:stone", "Terrain", 2, List.of(bind("mystcraft:BlockTerrain", 1), bind("mystcraft:BlockStructure", 2), bind("mystcraft:BlockSolid", 1))));
        register(def("mystcraft:ModMat_stone_1", "minecraft:stone", 1, "minecraft:granite", "Terrain", 2, List.of(bind("mystcraft:BlockTerrain", 2), bind("mystcraft:BlockStructure", 2), bind("mystcraft:BlockSolid", 1))));
        register(def("mystcraft:ModMat_stone_3", "minecraft:stone", 3, "minecraft:diorite", "Terrain", 2, List.of(bind("mystcraft:BlockTerrain", 2), bind("mystcraft:BlockStructure", 2), bind("mystcraft:BlockSolid", 1))));
        register(def("mystcraft:ModMat_stone_5", "minecraft:stone", 5, "minecraft:andesite", "Terrain", 2, List.of(bind("mystcraft:BlockTerrain", 2), bind("mystcraft:BlockStructure", 2), bind("mystcraft:BlockSolid", 1))));
        register(def("mystcraft:ModMat_stone_2", "minecraft:stone", 2, "minecraft:polished_granite", "Structure", 2, List.of(bind("mystcraft:BlockTerrain", 5), bind("mystcraft:BlockStructure", 1), bind("mystcraft:BlockSolid", 1))));
        register(def("mystcraft:ModMat_stone_4", "minecraft:stone", 4, "minecraft:polished_diorite", "Structure", 2, List.of(bind("mystcraft:BlockTerrain", 5), bind("mystcraft:BlockStructure", 1), bind("mystcraft:BlockSolid", 1))));
        register(def("mystcraft:ModMat_stone_6", "minecraft:stone", 6, "minecraft:polished_andesite", "Structure", 2, List.of(bind("mystcraft:BlockTerrain", 5), bind("mystcraft:BlockStructure", 1), bind("mystcraft:BlockSolid", 1))));
        register(def("mystcraft:ModMat_sandstone_0", "minecraft:sandstone", 0, "minecraft:sandstone", "Terrain", 2, List.of(bind("mystcraft:BlockTerrain", 2), bind("mystcraft:BlockStructure", 1), bind("mystcraft:BlockSolid", 1))));
        register(def("mystcraft:ModMat_netherrack_0", "minecraft:netherrack", 0, "minecraft:netherrack", "Terrain", 2, List.of(bind("mystcraft:BlockTerrain", 3), bind("mystcraft:BlockStructure", 2), bind("mystcraft:BlockSolid", 2))));
        register(def("mystcraft:ModMat_end_stone_0", "minecraft:end_stone", 0, "minecraft:end_stone", "Terrain", 3, List.of(bind("mystcraft:BlockTerrain", 4), bind("mystcraft:BlockStructure", 3), bind("mystcraft:BlockSolid", 3))));
        register(def("mystcraft:ModMat_nether_brick_0", "minecraft:nether_brick", 0, "minecraft:nether_bricks", "Structure", 2, List.of(bind("mystcraft:BlockSolid", 2), bind("mystcraft:BlockStructure", 2))));
        register(def("mystcraft:ModMat_log_0", "minecraft:log", 0, "minecraft:oak_log", "Structure", 2, List.of(bind("mystcraft:BlockSolid", 1), bind("mystcraft:BlockOrganic", 1), bind("mystcraft:BlockStructure", 1))));
        register(def("mystcraft:ModMat_log_1", "minecraft:log", 1, "minecraft:spruce_log", "Structure", 2, List.of(bind("mystcraft:BlockSolid", 1), bind("mystcraft:BlockOrganic", 1), bind("mystcraft:BlockStructure", 1))));
        register(def("mystcraft:ModMat_log_2", "minecraft:log", 2, "minecraft:birch_log", "Structure", 2, List.of(bind("mystcraft:BlockSolid", 1), bind("mystcraft:BlockOrganic", 1), bind("mystcraft:BlockStructure", 1))));
        register(def("mystcraft:ModMat_log_3", "minecraft:log", 3, "minecraft:jungle_log", "Structure", 2, List.of(bind("mystcraft:BlockSolid", 1), bind("mystcraft:BlockOrganic", 1), bind("mystcraft:BlockStructure", 1))));
        register(def("mystcraft:ModMat_log2_0", "minecraft:log2", 0, "minecraft:acacia_log", "Structure", 2, List.of(bind("mystcraft:BlockSolid", 1), bind("mystcraft:BlockOrganic", 1), bind("mystcraft:BlockStructure", 1))));
        register(def("mystcraft:ModMat_log2_1", "minecraft:log2", 1, "minecraft:dark_oak_log", "Structure", 2, List.of(bind("mystcraft:BlockSolid", 1), bind("mystcraft:BlockOrganic", 1), bind("mystcraft:BlockStructure", 1))));
        register(def("mystcraft:ModMat_diamond_ore_0", "minecraft:diamond_ore", 0, "minecraft:diamond_ore", "Ore", 5, List.of(bind("mystcraft:BlockSolid", 6), bind("mystcraft:BlockStructure", 6))));
        register(def("mystcraft:ModMat_gold_ore_0", "minecraft:gold_ore", 0, "minecraft:gold_ore", "Ore", 4, List.of(bind("mystcraft:BlockSolid", 5), bind("mystcraft:BlockStructure", 5))));
        register(def("mystcraft:ModMat_iron_ore_0", "minecraft:iron_ore", 0, "minecraft:iron_ore", "Ore", 3, List.of(bind("mystcraft:BlockSolid", 4), bind("mystcraft:BlockStructure", 4))));
        register(def("mystcraft:ModMat_coal_ore_0", "minecraft:coal_ore", 0, "minecraft:coal_ore", "Ore", 3, List.of(bind("mystcraft:BlockSolid", 4), bind("mystcraft:BlockStructure", 4))));
        register(def("mystcraft:ModMat_redstone_ore_0", "minecraft:redstone_ore", 0, "minecraft:redstone_ore", "Ore", 4, List.of(bind("mystcraft:BlockSolid", 5), bind("mystcraft:BlockStructure", 5))));
        register(def("mystcraft:ModMat_lapis_ore_0", "minecraft:lapis_ore", 0, "minecraft:lapis_ore", "Ore", 3, List.of(bind("mystcraft:BlockSolid", 4), bind("mystcraft:BlockStructure", 4))));
        register(def("mystcraft:ModMat_emerald_ore_0", "minecraft:emerald_ore", 0, "minecraft:emerald_ore", "Ore", 4, List.of(bind("mystcraft:BlockSolid", 5), bind("mystcraft:BlockStructure", 5))));
        register(def("mystcraft:ModMat_ice_0", "minecraft:ice", 0, "minecraft:ice", "Chain", 2, List.of(bind("mystcraft:BlockSolid", 3), bind("mystcraft:BlockFluid", 3), bind("mystcraft:BlockSea", 2), bind("mystcraft:BlockStructure", 3), bind("mystcraft:BlockCrystal", 3))));
        register(def("mystcraft:ModMat_packed_ice_0", "minecraft:packed_ice", 0, "minecraft:packed_ice", "Chain", 2, List.of(bind("mystcraft:BlockSolid", 3), bind("mystcraft:BlockFluid", 3), bind("mystcraft:BlockTerrain", 3), bind("mystcraft:BlockSea", 3), bind("mystcraft:BlockStructure", 3), bind("mystcraft:BlockCrystal", 3))));
        register(def("mystcraft:ModMat_glass_0", "minecraft:glass", 0, "minecraft:glass", "Chain", 2, List.of(bind("mystcraft:BlockSolid", 3), bind("mystcraft:BlockStructure", 3), bind("mystcraft:BlockCrystal", 3))));
        register(def("mystcraft:ModMat_snow_0", "minecraft:snow_block", 0, "minecraft:snow_block", "Chain", 2, List.of(bind("mystcraft:BlockSolid", 3), bind("mystcraft:BlockStructure", 3), bind("mystcraft:BlockCrystal", 3)))); // 1.12 Blocks.SNOW was the full snow block; modern minecraft:snow is the layer.
        register(def("mystcraft:ModMat_obsidian_0", "minecraft:obsidian", 0, "minecraft:obsidian", "Chain", 3, List.of(bind("mystcraft:BlockSolid", 4), bind("mystcraft:BlockTerrain", 4), bind("mystcraft:BlockStructure", 3), bind("mystcraft:BlockCrystal", 3))));
        register(def("mystcraft:ModMat_glowstone_0", "minecraft:glowstone", 0, "minecraft:glowstone", "Chain", 3, List.of(bind("mystcraft:BlockSolid", 4), bind("mystcraft:BlockStructure", 4), bind("mystcraft:BlockCrystal", 4))));
        register(def("mystcraft:ModMat_quartz_ore_0", "minecraft:quartz_ore", 0, "minecraft:nether_quartz_ore", "Chain", 3, List.of(bind("mystcraft:BlockSolid", 4), bind("mystcraft:BlockStructure", 4), bind("mystcraft:BlockCrystal", 4))));
        register(def("mystcraft:ModMat_blockcrystal_0", "mystcraft:blockcrystal", 0, "mystcraft:blockcrystal", "Chain", 3, List.of(bind("mystcraft:BlockSolid", 4), bind("mystcraft:BlockStructure", 4), bind("mystcraft:BlockCrystal", 4))));
        register(def("mystcraft:ModMat_water_0", "minecraft:water", 0, "minecraft:water", "Sea", 2, List.of(bind("mystcraft:BlockFluid", 1), bind("mystcraft:BlockSea", 1))));
        register(def("mystcraft:ModMat_lava_0", "minecraft:lava", 0, "minecraft:lava", "Sea", 3, List.of(bind("mystcraft:BlockFluid", 2), bind("mystcraft:BlockSea", 2))));
        bootstrapped = true;
    }


    /**
     * Recreates ModSymbolsFluids.modsLoaded(): every registered non-gaseous fluid
     * with a real block representation receives a Sea/Fluid material symbol. Water
     * and lava are skipped because their fixed 1.12 symbols are already registered.
     * Instability factors are retained for score-only diagnostics. Runtime penalties
     * remain independently gated by InstabilityPolicy.
     */
    public static synchronized boolean bootstrapRuntimeFluids() {
        bootstrapDefaults();
        if (!runtimeFluidsDirty) return false;
        ArrayList<ResourceLocation> fluidKeys = new ArrayList<>(BuiltInRegistries.FLUID.keySet());
        fluidKeys.sort(java.util.Comparator.comparing(ResourceLocation::toString));

        for (String id : RUNTIME_FLUID_IDS) BY_LEGACY_ID.remove(id);
        RUNTIME_FLUID_IDS.clear();

        for (ResourceLocation fluidKey : fluidKeys) {
            Fluid fluid = BuiltInRegistries.FLUID.get(fluidKey);
            if (fluid == Fluids.EMPTY || fluid == Fluids.WATER || fluid == Fluids.FLOWING_WATER
                    || fluid == Fluids.LAVA || fluid == Fluids.FLOWING_LAVA) continue;
            if (isRuntimeFluidBlacklisted(fluidKey, fluid)) continue;

            FluidStack probe = new FluidStack(fluid, FluidType.BUCKET_VOLUME);
            if (probe.getFluidType().getDensity() <= 0) continue;

            BlockState fluidBlockState = fluid.defaultFluidState().createLegacyBlock();
            Block block = fluidBlockState.getBlock();
            if (block == Blocks.AIR) continue;
            ResourceLocation blockKey = BuiltInRegistries.BLOCK.getKey(block);
            if (blockKey == null) continue;

            String symbolNamespace = blockKey.getNamespace().equals("minecraft") ? "mystcraft" : blockKey.getNamespace();
            String legacyId = symbolNamespace + ":ModMat_" + blockKey.getPath() + "_0";
            if (BY_LEGACY_ID.containsKey(LegacySymbolId.qualify(legacyId))) continue;

            RuntimeFluidOptions options = FLUID_OPTIONS.getOrDefault(fluidKey, RuntimeFluidOptions.DEFAULT);
            ArrayList<LegacyMaterialGrammarBinding> bindings = new ArrayList<>();
            if (!options.seaBanned()) bindings.add(bind("mystcraft:BlockSea", options.grammarRank()));
            bindings.add(bind("mystcraft:BlockFluid", options.grammarRank()));
            LegacyMaterialSymbolDefinition definition = def(
                    legacyId,
                    blockKey.toString(),
                    0,
                    blockKey.toString(),
                    "Sea",
                    options.cardRank(),
                    bindings);
            register(definition);
            RUNTIME_FLUID_IDS.add(definition.legacyId());
        }
        runtimeFluidsDirty = false;
        return true;
    }

    public static synchronized void blacklistRuntimeFluid(ResourceLocation fluidId) {
        if (fluidId == null) return;
        boolean changed = FLUID_BLACKLIST.add(fluidId);
        Fluid target = BuiltInRegistries.FLUID.get(fluidId);
        if (target != null && target != Fluids.EMPTY) {
            Block targetBlock = target.defaultFluidState().createLegacyBlock().getBlock();
            if (targetBlock != Blocks.AIR) {
                for (ResourceLocation key : BuiltInRegistries.FLUID.keySet()) {
                    Fluid candidate = BuiltInRegistries.FLUID.get(key);
                    if (candidate != null && candidate != Fluids.EMPTY
                            && candidate.defaultFluidState().createLegacyBlock().getBlock() == targetBlock) {
                        changed |= FLUID_BLACKLIST.add(key);
                    }
                }
            }
        }
        if (changed) runtimeFluidsDirty = true;
    }

    /** Applies legacy fluidsymboldata fields, including score-only instability factors. */
    public static synchronized void configureRuntimeFluid(
            ResourceLocation fluidId, Boolean seaBanned, Integer cardRank, Integer grammarRank) {
        configureRuntimeFluid(fluidId, seaBanned, cardRank, grammarRank, null, null);
    }

    public static synchronized void configureRuntimeFluid(
            ResourceLocation fluidId, Boolean seaBanned, Integer cardRank, Integer grammarRank, Float factor1, Float factor2) {
        if (fluidId == null) return;
        RuntimeFluidOptions current = FLUID_OPTIONS.getOrDefault(fluidId, RuntimeFluidOptions.DEFAULT);
        RuntimeFluidOptions next = new RuntimeFluidOptions(
                seaBanned != null ? seaBanned : current.seaBanned(),
                cardRank != null ? Math.max(0, cardRank) : current.cardRank(),
                grammarRank != null ? Math.max(0, grammarRank) : current.grammarRank(),
                factor1 != null ? factor1 : current.factor1(),
                factor2 != null ? factor2 : current.factor2());
        FLUID_OPTIONS.put(fluidId, next);

        Fluid target = BuiltInRegistries.FLUID.get(fluidId);
        if (target != null && target != Fluids.EMPTY) {
            Block targetBlock = target.defaultFluidState().createLegacyBlock().getBlock();
            if (targetBlock != Blocks.AIR) {
                for (ResourceLocation key : BuiltInRegistries.FLUID.keySet()) {
                    Fluid candidate = BuiltInRegistries.FLUID.get(key);
                    if (candidate != null && candidate != Fluids.EMPTY
                            && candidate.defaultFluidState().createLegacyBlock().getBlock() == targetBlock) {
                        FLUID_OPTIONS.put(key, next);
                    }
                }
            }
        }
        runtimeFluidsDirty = true;
    }

    private static boolean isRuntimeFluidBlacklisted(ResourceLocation key, Fluid fluid) {
        if (FLUID_BLACKLIST.contains(key)) return true;
        Block block = fluid.defaultFluidState().createLegacyBlock().getBlock();
        if (block == Blocks.AIR) return false;
        for (ResourceLocation blacklisted : FLUID_BLACKLIST) {
            Fluid other = BuiltInRegistries.FLUID.get(blacklisted);
            if (other != null && other != Fluids.EMPTY
                    && other.defaultFluidState().createLegacyBlock().getBlock() == block) return true;
        }
        return false;
    }

    private record RuntimeFluidOptions(boolean seaBanned, int cardRank, int grammarRank, float factor1, float factor2) {
        private static final RuntimeFluidOptions DEFAULT = new RuntimeFluidOptions(false, 4, 4, 1.0F, 0.25F);
    }

    /** Returns legacy factor1/factor2 for the runtime fluid represented by this block id. */
    public static synchronized float[] runtimeFluidInstabilityFactors(ResourceLocation blockId) {
        if (blockId == null) return new float[]{1.0F, 0.25F};
        for (Map.Entry<ResourceLocation, RuntimeFluidOptions> entry : FLUID_OPTIONS.entrySet()) {
            Fluid fluid = BuiltInRegistries.FLUID.get(entry.getKey());
            if (fluid == null || fluid == Fluids.EMPTY) continue;
            Block block = fluid.defaultFluidState().createLegacyBlock().getBlock();
            if (blockId.equals(BuiltInRegistries.BLOCK.getKey(block))) {
                RuntimeFluidOptions o = entry.getValue();
                return new float[]{o.factor1(), o.factor2()};
            }
        }
        return new float[]{1.0F, 0.25F};
    }

    public static synchronized int runtimeFluidSize() {
        return RUNTIME_FLUID_IDS.size();
    }

    /** Eligible block-backed non-gaseous fluid blocks after legacy blacklist policy. */
    public static synchronized Set<ResourceLocation> runtimeEligibleFluidBlockIds() {
        LinkedHashSet<ResourceLocation> result = new LinkedHashSet<>();
        for (ResourceLocation fluidKey : BuiltInRegistries.FLUID.keySet()) {
            Fluid fluid = BuiltInRegistries.FLUID.get(fluidKey);
            if (fluid == Fluids.EMPTY || fluid == Fluids.WATER || fluid == Fluids.FLOWING_WATER
                    || fluid == Fluids.LAVA || fluid == Fluids.FLOWING_LAVA) continue;
            if (isRuntimeFluidBlacklisted(fluidKey, fluid)) continue;
            FluidStack probe = new FluidStack(fluid, FluidType.BUCKET_VOLUME);
            if (probe.getFluidType().getDensity() <= 0) continue;
            Block block = fluid.defaultFluidState().createLegacyBlock().getBlock();
            if (block == Blocks.AIR) continue;
            ResourceLocation blockKey = BuiltInRegistries.BLOCK.getKey(block);
            if (blockKey != null) result.add(blockKey);
        }
        return Set.copyOf(result);
    }

    /** Runtime-fluid material symbols currently materialized, deduplicated by block. */
    public static synchronized Set<ResourceLocation> runtimeRegisteredFluidBlockIds() {
        LinkedHashSet<ResourceLocation> result = new LinkedHashSet<>();
        for (String legacyId : RUNTIME_FLUID_IDS) {
            LegacyMaterialSymbolDefinition definition = BY_LEGACY_ID.get(legacyId);
            if (definition == null) continue;
            ResourceLocation blockId = ResourceLocation.tryParse(definition.modernBlockId());
            if (blockId != null) result.add(blockId);
        }
        return Set.copyOf(result);
    }

    private static LegacyMaterialSymbolDefinition def(
            String legacyId,
            String legacyBlockId,
            int legacyMetadata,
            String modernBlockId,
            String legacyWord,
            int cardRank,
            List<LegacyMaterialGrammarBinding> bindings) {
        return new LegacyMaterialSymbolDefinition(
                legacyId, legacyBlockId, legacyMetadata, modernBlockId, legacyWord, cardRank, bindings);
    }

    private static LegacyMaterialGrammarBinding bind(String parent, int rank) {
        return new LegacyMaterialGrammarBinding(parent, rank);
    }

    private static void register(LegacyMaterialSymbolDefinition definition) {
        LegacyMaterialSymbolDefinition existing = BY_LEGACY_ID.putIfAbsent(definition.legacyId(), definition);
        if (existing != null && !existing.equals(definition)) {
            throw new IllegalStateException("Duplicate legacy material symbol id: " + definition.legacyId());
        }
    }

    public static Optional<LegacyMaterialSymbolDefinition> resolveLegacy(String legacyId) {
        bootstrapDefaults();
        return Optional.ofNullable(BY_LEGACY_ID.get(LegacySymbolId.qualify(legacyId)));
    }

    public static boolean containsLegacy(String legacyId) {
        return resolveLegacy(legacyId).isPresent();
    }

    public static Collection<LegacyMaterialSymbolDefinition> values() {
        bootstrapDefaults();
        return Collections.unmodifiableList(new ArrayList<>(BY_LEGACY_ID.values()));
    }

    public static List<LegacyMaterialSymbolDefinition> usableAs(String parentToken) {
        bootstrapDefaults();
        List<LegacyMaterialSymbolDefinition> result = new ArrayList<>();
        for (LegacyMaterialSymbolDefinition definition : BY_LEGACY_ID.values()) {
            if (definition.usableAs(parentToken)) result.add(definition);
        }
        return List.copyOf(result);
    }

    public static int size() {
        bootstrapDefaults();
        return BY_LEGACY_ID.size();
    }
}
